env:
  TERM: xterm-256color

live_config_reload: true
scrolling:
    history: 10000
    multiplier: 10
selection:
    semantic_escape_chars: '|:"'' {}()[]<>'
    save_to_clipboard: true
window:
  opacity: 1.0
  padding:
    x: 10
    y: 5
  # decorations: "Buttonless"

font:
  normal:
    family: "JetBrainsMono Nerd Font Mono"
    style: Regular
  bold:
    family: "JetBrainsMono Nerd Font Mono"
    style: Bold
  italic:
    family: "JetBrainsMono Nerd Font Mono"
    style: Italic
  bold_italic:
    family: "JetBrainsMono Nerd Font Mono"
    style: Bold Italic
  size: 14
  offset:
    y: 10
  glyph_offset:
    y: 9

draw_bold_text_with_bright_colors: true

# TokyoNight Alacritty Colors
colors:
  # Default colors
  primary:
    background: '0x1a1b26'
    foreground: '0xc0caf5'

  # Normal colors
  normal:
    black:   '0x15161E'
    red:     '0xf7768e'
    green:   '0x9ece6a'
    yellow:  '0xe0af68'
    blue:    '0x7aa2f7'
    magenta: '0xbb9af7'
    cyan:    '0x7dcfff'
    white:   '0xa9b1d6'

  # Bright colors
  bright:
    black:   '0x414868'
    red:     '0xf7768e'
    green:   '0x9ece6a'
    yellow:  '0xe0af68'
    blue:    '0x7aa2f7'
    magenta: '0xbb9af7'
    cyan:    '0x7dcfff'
    white:   '0xc0caf5'

  indexed_colors:
    - { index: 16, color: '0xff9e64' }
    - { index: 17, color: '0xdb4b4b' }

cursor:
  style: Block
  unfocused_hollow: true

key_bindings:
  - { key: N,      mods: Command,         action: SpawnNewInstance }
  - { key: Q,      mods: Command,         action: Quit             }
  - { key: W,      mods: Command,         action: Quit             }
  - { key: F,      mods: Command|Control, action: ToggleFullscreen }
  # - { key: Z,      mods: Control, chars: "\x1bz" }
