"$schema" = 'https://starship.rs/config-schema.json'
command_timeout = 1000

format = """
$directory\
$git_branch\
$git_status\
$python\
$kubernetes\
$cmd_duration\
$status\
$jobs\
$fill\
$time\
$line_break$character"""

palette = 'tomorrow_night_eighties'

[palettes.tomorrow_night_eighties]
color_bg3 = '#999999'
color_blue = '#6699cc'
color_aqua = '#66cccc'
color_green = '#99cc99'
color_orange = '#f99157'
color_purple = '#cc99cc'
color_red = '#f2777a'
color_yellow = '#ffcc66'

[directory]
style = "fg:color_yellow"
repo_root_style = "fg:color_yellow bold"
format = "[$path]($style) "
repo_root_format = "[$before_root_path]($style)[$repo_root]($repo_root_style)[$path]($style) "
truncation_length = 5
truncate_to_repo = false
truncation_symbol = "…/"

[git_branch]
symbol = " "
style = "fg:color_aqua"
format = '[$symbol$branch]($style) '

[git_status]
style = "fg:color_red"
format = '([$all_status$ahead_behind]($style) )'

[python]
style = "fg:color_blue"
format = '([ $virtualenv]($style) )'

[kubernetes]
disabled = true
style = "fg:color_bg3"
format = '([$symbol$context]($style) )'

[[kubernetes.contexts]]
context_pattern = "intprod"
context_alias = "intprod"
style = "fg:color_orange bold"
symbol = "Δ "

[[kubernetes.contexts]]
context_pattern = "produswest2"
context_alias = "produswest2"
style = "fg:color_red bold"
symbol = "⚠︎ "

[[kubernetes.contexts]]
context_pattern = "prodeucentral1"
context_alias = "prodeucentral1"
style = "fg:color_red bold"
symbol = "⚠︎ "

[cmd_duration]
min_time = 2000
style = "fg:color_bg3"
format = '[$duration]($style) '

[status]
disabled = false
style = "fg:color_red"
format = '[$status]($style) '

[fill]
symbol = " "

[time]
disabled = false
time_format = "%R"
style = "fg:color_bg3"
format = '[$time]($style)'

[jobs]
symbol = " "
style = "fg:color_red"
number_threshold = 1
format = '[$symbol]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[❯](bold fg:color_green)'
error_symbol = '[❯](bold fg:color_red)'
vimcmd_symbol = '[❮](bold fg:color_green)'
vimcmd_replace_one_symbol = '[❮](bold fg:color_purple)'
vimcmd_replace_symbol = '[❮](bold fg:color_purple)'
vimcmd_visual_symbol = '[❮](bold fg:color_yellow)'
