require("user.options")
require("user.keymaps")
require("user.plugins")

require("user.colorscheme")
require("user.lualine")
require("user.bufferline")
require("user.lsp")
require("user.treesitter")
require("user.tree")
require("user.telescope")
require("user.toggleterm")
require("user.debug")
require("user.null-ls")
